from typing import Annotated

from numpy.typing import ArrayLike

class IntVector:
    def from_buffer(self) -> IntVector: ...

    def to_buffer(self) -> Annotated[ArrayLike, dict(dtype='int32', order='C')]: ...

class Matrix:
    def __init__(self) -> None: ...

    def from_buffer(self) -> Matrix: ...

    def to_buffer(self) -> Annotated[ArrayLike, dict(dtype='float64', order='C')]: ...

def aca(arg0: Matrix, arg1: int, arg2: int, arg3: int, arg4: int, arg5: Matrix, arg6: Matrix, arg7: IntVector, arg8: float, arg9: float, arg10: float, arg11: float, arg12: IntVector, arg13: IntVector, arg14: int, /) -> None: ...

def maxvol(arg0: Matrix, arg1: int, arg2: int, arg3: int, arg4: IntVector, arg5: IntVector, arg6: Matrix, arg7: Matrix, arg8: int, arg9: int, arg10: Matrix, arg11: bool, /) -> None: ...

def maxvol_proj(arg0: Matrix, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: IntVector, arg7: IntVector, arg8: Matrix, arg9: Matrix, arg10: int, arg11: int, arg12: "AccType", /) -> None: ...
